# Generated by Django 5.0.6 on 2024-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensesapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="nombre",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
